# Generated by Django 5.1.2 on 2024-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attached_files',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
