# Generated by Django 5.1.2 on 2024-12-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_attached_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='attached_files',
        ),
        migrations.AddField(
            model_name='project',
            name='attached_files',
            field=models.ManyToManyField(blank=True, to='api.projectfile'),
        ),
    ]
