# Generated by Django 5.1.2 on 2024-12-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectfile_remove_project_attached_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
