# Generated by Django 5.1.4 on 2025-06-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_is_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_tags', models.JSONField(blank=True, default=list, help_text='List of tags to exclude from similarity calculations', null=True)),
                ('excluded_technologies', models.JSONField(blank=True, default=list, help_text='List of technologies to exclude from similarity calculations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relation Settings',
                'verbose_name_plural': 'Relation Settings',
            },
        ),
    ]
